// src/components/booking/MobileStickyBar.tsx
"use client";

import Link from "next/link";
import { MessageCircle } from "lucide-react";

export function MobileStickyBar({
  propertyId,
}: {
  propertyId: string;
}) {
  function openChat() {
    window.dispatchEvent(new CustomEvent("open-concierge-chat"));
  }

  return (
    <div className="fixed inset-x-4 bottom-3 z-40 md:hidden">
      <div className="mx-auto flex max-w-sm translate-y-1 items-center gap-2 rounded-full border border-border/80 bg-background/90 p-2 shadow-2xl shadow-black/25 backdrop-blur-xl transition-transform duration-300 focus-within:translate-y-0 hover:translate-y-0 dark:bg-card/90">
        <Link
          href={`/booking?unit=${propertyId}`}
          className="flex h-12 flex-1 items-center justify-center rounded-full bg-gold px-5 text-sm font-semibold text-navy shadow-lg shadow-gold/20 transition hover:bg-gold-light"
        >
          Book
        </Link>
        <button
          type="button"
          onClick={openChat}
          className="flex h-12 w-12 shrink-0 items-center justify-center rounded-full border border-border bg-card text-foreground shadow-sm transition hover:bg-muted"
          aria-label="Open concierge chat"
        >
          <MessageCircle className="h-5 w-5" />
        </button>
      </div>
    </div>
  );
}

// src/lib/components/urgency/MobileStickyBar.svelte
<script lang="ts">
	import { getDiscountedPrice } from '$lib/data/urgency';
	import { bookingState } from '$lib/stores/booking.svelte';

	let {
		pricePerNight,
		propertyId
	}: {
		pricePerNight: number;
		propertyId: string;
	} = $props();

	const discounted = $derived(getDiscountedPrice(pricePerNight));

	function handleReserve() {
		bookingState.startBooking(propertyId);
	}
</script>

<div class="fixed bottom-0 left-0 right-0 z-40 border-t border-border bg-card px-4 py-3 shadow-[0_-4px_20px_rgba(0,0,0,0.1)] md:hidden">
	<div class="flex items-center justify-between">
		<div>
			<div class="flex items-baseline gap-1.5">
				<span class="text-sm text-muted-foreground line-through">&#3647;{pricePerNight.toLocaleString()}</span>
				<span class="text-lg font-bold text-card-foreground">&#3647;{discounted.toLocaleString()}</span>
			</div>
			<p class="text-[11px] text-muted-foreground">/night</p>
		</div>
		<button
			onclick={handleReserve}
			class="rounded-xl bg-gradient-to-r from-sky-500 to-blue-600 px-5 py-2.5 text-sm font-semibold text-white shadow-lg transition hover:from-sky-400 hover:to-blue-500"
		>
			Reserve Now
		</button>
	</div>
</div>
